# App
spring.application.name=delivery-fee

# Server
server.port=8080

# Logging
logging.level.org.springframework=INFO

# ======================
# H2 DATABASE
# ======================
spring.datasource.url=jdbc:h2:mem:deliveryfee
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# H2 CONSOLE
# ======================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

weather.import.cron=0 15 * * * *

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html